# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 21:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='accel', max_length=32)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('user', 'start_date', 'end_date')]),
        ),
        migrations.AlterIndexTogether(
            name='dataset',
            index_together=set([('user', 'start_date', 'end_date'), ('type', 'start_date', 'end_date'), ('start_date', 'end_date')]),
        ),
    ]
